// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"flag"
	"fmt"
	"github.com/XiaoMi/galaxy-sdk-go/thrift"
	"math"
	"net"
	"net/url"
	"os"
	"sds/admin"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  void saveAppInfo(AppInfo appInfo)")
	fmt.Fprintln(os.Stderr, "  AppInfo getAppInfo(string appId)")
	fmt.Fprintln(os.Stderr, "   findAllApps()")
	fmt.Fprintln(os.Stderr, "   findAllTables()")
	fmt.Fprintln(os.Stderr, "  TableInfo createTable(string tableName, TableSpec tableSpec)")
	fmt.Fprintln(os.Stderr, "  void dropTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  void lazyDropTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  void alterTable(string tableName, TableSpec tableSpec)")
	fmt.Fprintln(os.Stderr, "  void cloneTable(string srcName, string destTable, bool flushTable)")
	fmt.Fprintln(os.Stderr, "  void disableTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  void enableTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  TableSpec describeTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  TableStatus getTableStatus(string tableName)")
	fmt.Fprintln(os.Stderr, "  TableState getTableState(string tableName)")
	fmt.Fprintln(os.Stderr, "   getTableSplits(string tableName, Dictionary startKey, Dictionary stopKey)")
	fmt.Fprintln(os.Stderr, "  TimeSeriesData queryMetric(MetricQueryRequest query)")
	fmt.Fprintln(os.Stderr, "   queryMetrics( queries)")
	fmt.Fprintln(os.Stderr, "   findAllAppInfo()")
	fmt.Fprintln(os.Stderr, "  Version getServerVersion()")
	fmt.Fprintln(os.Stderr, "  void validateClientVersion(Version clientVersion)")
	fmt.Fprintln(os.Stderr, "  i64 getServerTime()")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := admin.NewAdminServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "saveAppInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveAppInfo requires 1 args")
			flag.Usage()
		}
		arg53 := flag.Arg(1)
		mbTrans54 := thrift.NewTMemoryBufferLen(len(arg53))
		defer mbTrans54.Close()
		_, err55 := mbTrans54.WriteString(arg53)
		if err55 != nil {
			Usage()
			return
		}
		factory56 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt57 := factory56.GetProtocol(mbTrans54)
		argvalue0 := admin.NewAppInfo()
		err58 := argvalue0.Read(jsProt57)
		if err58 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveAppInfo(value0))
		fmt.Print("\n")
		break
	case "getAppInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetAppInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetAppInfo(value0))
		fmt.Print("\n")
		break
	case "findAllApps":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "FindAllApps requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.FindAllApps())
		fmt.Print("\n")
		break
	case "findAllTables":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "FindAllTables requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.FindAllTables())
		fmt.Print("\n")
		break
	case "createTable":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "CreateTable requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		arg61 := flag.Arg(2)
		mbTrans62 := thrift.NewTMemoryBufferLen(len(arg61))
		defer mbTrans62.Close()
		_, err63 := mbTrans62.WriteString(arg61)
		if err63 != nil {
			Usage()
			return
		}
		factory64 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt65 := factory64.GetProtocol(mbTrans62)
		argvalue1 := admin.NewTableSpec()
		err66 := argvalue1.Read(jsProt65)
		if err66 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.CreateTable(value0, value1))
		fmt.Print("\n")
		break
	case "dropTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DropTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DropTable(value0))
		fmt.Print("\n")
		break
	case "lazyDropTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "LazyDropTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.LazyDropTable(value0))
		fmt.Print("\n")
		break
	case "alterTable":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "AlterTable requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		arg70 := flag.Arg(2)
		mbTrans71 := thrift.NewTMemoryBufferLen(len(arg70))
		defer mbTrans71.Close()
		_, err72 := mbTrans71.WriteString(arg70)
		if err72 != nil {
			Usage()
			return
		}
		factory73 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt74 := factory73.GetProtocol(mbTrans71)
		argvalue1 := admin.NewTableSpec()
		err75 := argvalue1.Read(jsProt74)
		if err75 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.AlterTable(value0, value1))
		fmt.Print("\n")
		break
	case "cloneTable":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "CloneTable requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3) == "true"
		value2 := argvalue2
		fmt.Print(client.CloneTable(value0, value1, value2))
		fmt.Print("\n")
		break
	case "disableTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DisableTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DisableTable(value0))
		fmt.Print("\n")
		break
	case "enableTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "EnableTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.EnableTable(value0))
		fmt.Print("\n")
		break
	case "describeTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DescribeTable(value0))
		fmt.Print("\n")
		break
	case "getTableStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTableStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetTableStatus(value0))
		fmt.Print("\n")
		break
	case "getTableState":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTableState requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetTableState(value0))
		fmt.Print("\n")
		break
	case "getTableSplits":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "GetTableSplits requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		arg85 := flag.Arg(2)
		mbTrans86 := thrift.NewTMemoryBufferLen(len(arg85))
		defer mbTrans86.Close()
		_, err87 := mbTrans86.WriteString(arg85)
		if err87 != nil {
			Usage()
			return
		}
		factory88 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt89 := factory88.GetProtocol(mbTrans86)
		containerStruct1 := admin.NewGetTableSplitsArgs()
		err90 := containerStruct1.ReadField2(jsProt89)
		if err90 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.StartKey
		value1 := admin.Dictionary(argvalue1)
		arg91 := flag.Arg(3)
		mbTrans92 := thrift.NewTMemoryBufferLen(len(arg91))
		defer mbTrans92.Close()
		_, err93 := mbTrans92.WriteString(arg91)
		if err93 != nil {
			Usage()
			return
		}
		factory94 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt95 := factory94.GetProtocol(mbTrans92)
		containerStruct2 := admin.NewGetTableSplitsArgs()
		err96 := containerStruct2.ReadField3(jsProt95)
		if err96 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.StopKey
		value2 := admin.Dictionary(argvalue2)
		fmt.Print(client.GetTableSplits(value0, value1, value2))
		fmt.Print("\n")
		break
	case "queryMetric":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryMetric requires 1 args")
			flag.Usage()
		}
		arg97 := flag.Arg(1)
		mbTrans98 := thrift.NewTMemoryBufferLen(len(arg97))
		defer mbTrans98.Close()
		_, err99 := mbTrans98.WriteString(arg97)
		if err99 != nil {
			Usage()
			return
		}
		factory100 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt101 := factory100.GetProtocol(mbTrans98)
		argvalue0 := admin.NewMetricQueryRequest()
		err102 := argvalue0.Read(jsProt101)
		if err102 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryMetric(value0))
		fmt.Print("\n")
		break
	case "queryMetrics":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryMetrics requires 1 args")
			flag.Usage()
		}
		arg103 := flag.Arg(1)
		mbTrans104 := thrift.NewTMemoryBufferLen(len(arg103))
		defer mbTrans104.Close()
		_, err105 := mbTrans104.WriteString(arg103)
		if err105 != nil {
			Usage()
			return
		}
		factory106 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt107 := factory106.GetProtocol(mbTrans104)
		containerStruct0 := admin.NewQueryMetricsArgs()
		err108 := containerStruct0.ReadField1(jsProt107)
		if err108 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.Queries
		value0 := argvalue0
		fmt.Print(client.QueryMetrics(value0))
		fmt.Print("\n")
		break
	case "findAllAppInfo":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "FindAllAppInfo requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.FindAllAppInfo())
		fmt.Print("\n")
		break
	case "getServerVersion":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetServerVersion requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetServerVersion())
		fmt.Print("\n")
		break
	case "validateClientVersion":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ValidateClientVersion requires 1 args")
			flag.Usage()
		}
		arg109 := flag.Arg(1)
		mbTrans110 := thrift.NewTMemoryBufferLen(len(arg109))
		defer mbTrans110.Close()
		_, err111 := mbTrans110.WriteString(arg109)
		if err111 != nil {
			Usage()
			return
		}
		factory112 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt113 := factory112.GetProtocol(mbTrans110)
		argvalue0 := admin.NewVersion()
		err114 := argvalue0.Read(jsProt113)
		if err114 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ValidateClientVersion(value0))
		fmt.Print("\n")
		break
	case "getServerTime":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetServerTime requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetServerTime())
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
