// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"flag"
	"fmt"
	"github.com/XiaoMi/galaxy-sdk-go/thrift"
	"math"
	"net"
	"net/url"
	"os"
	"sds/admin"
	"strconv"
	"strings"
)

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  void saveAppInfo(AppInfo appInfo)")
	fmt.Fprintln(os.Stderr, "  AppInfo getAppInfo(string appId)")
	fmt.Fprintln(os.Stderr, "   findAllApps()")
	fmt.Fprintln(os.Stderr, "   findAllTables()")
	fmt.Fprintln(os.Stderr, "   cleanAllLazyDroppedTables()")
	fmt.Fprintln(os.Stderr, "  TableInfo createTable(string tableName, TableSpec tableSpec)")
	fmt.Fprintln(os.Stderr, "  void dropTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  void restoreTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  void alterTable(string tableName, TableSpec tableSpec)")
	fmt.Fprintln(os.Stderr, "  void cloneTable(string srcName, string destTable, bool flushTable)")
	fmt.Fprintln(os.Stderr, "  void disableTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  void enableTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  TableSpec describeTable(string tableName)")
	fmt.Fprintln(os.Stderr, "  TableStatus getTableStatus(string tableName)")
	fmt.Fprintln(os.Stderr, "  TableState getTableState(string tableName)")
	fmt.Fprintln(os.Stderr, "   getTableSplits(string tableName, Dictionary startKey, Dictionary stopKey)")
	fmt.Fprintln(os.Stderr, "  TimeSeriesData queryMetric(MetricQueryRequest query)")
	fmt.Fprintln(os.Stderr, "   queryMetrics( queries)")
	fmt.Fprintln(os.Stderr, "   findAllAppInfo()")
	fmt.Fprintln(os.Stderr, "  i64 getTableSize(string tableName)")
	fmt.Fprintln(os.Stderr, "  Version getServerVersion()")
	fmt.Fprintln(os.Stderr, "  void validateClientVersion(Version clientVersion)")
	fmt.Fprintln(os.Stderr, "  i64 getServerTime()")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	var parsedUrl url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Parse()

	if len(urlString) > 0 {
		parsedUrl, err := url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}

	cmd := flag.Arg(0)
	var err error
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransport(trans)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactory()
		break
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
		break
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
		break
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	client := admin.NewAdminServiceClientFactory(trans, protocolFactory)
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}

	switch cmd {
	case "saveAppInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveAppInfo requires 1 args")
			flag.Usage()
		}
		arg58 := flag.Arg(1)
		mbTrans59 := thrift.NewTMemoryBufferLen(len(arg58))
		defer mbTrans59.Close()
		_, err60 := mbTrans59.WriteString(arg58)
		if err60 != nil {
			Usage()
			return
		}
		factory61 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt62 := factory61.GetProtocol(mbTrans59)
		argvalue0 := admin.NewAppInfo()
		err63 := argvalue0.Read(jsProt62)
		if err63 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveAppInfo(value0))
		fmt.Print("\n")
		break
	case "getAppInfo":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetAppInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetAppInfo(value0))
		fmt.Print("\n")
		break
	case "findAllApps":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "FindAllApps requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.FindAllApps())
		fmt.Print("\n")
		break
	case "findAllTables":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "FindAllTables requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.FindAllTables())
		fmt.Print("\n")
		break
	case "cleanAllLazyDroppedTables":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "CleanAllLazyDroppedTables requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.CleanAllLazyDroppedTables())
		fmt.Print("\n")
		break
	case "createTable":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "CreateTable requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		arg66 := flag.Arg(2)
		mbTrans67 := thrift.NewTMemoryBufferLen(len(arg66))
		defer mbTrans67.Close()
		_, err68 := mbTrans67.WriteString(arg66)
		if err68 != nil {
			Usage()
			return
		}
		factory69 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt70 := factory69.GetProtocol(mbTrans67)
		argvalue1 := admin.NewTableSpec()
		err71 := argvalue1.Read(jsProt70)
		if err71 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.CreateTable(value0, value1))
		fmt.Print("\n")
		break
	case "dropTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DropTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DropTable(value0))
		fmt.Print("\n")
		break
	case "restoreTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "RestoreTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.RestoreTable(value0))
		fmt.Print("\n")
		break
	case "alterTable":
		if flag.NArg()-1 != 2 {
			fmt.Fprintln(os.Stderr, "AlterTable requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		arg75 := flag.Arg(2)
		mbTrans76 := thrift.NewTMemoryBufferLen(len(arg75))
		defer mbTrans76.Close()
		_, err77 := mbTrans76.WriteString(arg75)
		if err77 != nil {
			Usage()
			return
		}
		factory78 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt79 := factory78.GetProtocol(mbTrans76)
		argvalue1 := admin.NewTableSpec()
		err80 := argvalue1.Read(jsProt79)
		if err80 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.AlterTable(value0, value1))
		fmt.Print("\n")
		break
	case "cloneTable":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "CloneTable requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3) == "true"
		value2 := argvalue2
		fmt.Print(client.CloneTable(value0, value1, value2))
		fmt.Print("\n")
		break
	case "disableTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DisableTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DisableTable(value0))
		fmt.Print("\n")
		break
	case "enableTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "EnableTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.EnableTable(value0))
		fmt.Print("\n")
		break
	case "describeTable":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "DescribeTable requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DescribeTable(value0))
		fmt.Print("\n")
		break
	case "getTableStatus":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTableStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetTableStatus(value0))
		fmt.Print("\n")
		break
	case "getTableState":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTableState requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetTableState(value0))
		fmt.Print("\n")
		break
	case "getTableSplits":
		if flag.NArg()-1 != 3 {
			fmt.Fprintln(os.Stderr, "GetTableSplits requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		arg90 := flag.Arg(2)
		mbTrans91 := thrift.NewTMemoryBufferLen(len(arg90))
		defer mbTrans91.Close()
		_, err92 := mbTrans91.WriteString(arg90)
		if err92 != nil {
			Usage()
			return
		}
		factory93 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt94 := factory93.GetProtocol(mbTrans91)
		containerStruct1 := admin.NewGetTableSplitsArgs()
		err95 := containerStruct1.ReadField2(jsProt94)
		if err95 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.StartKey
		value1 := admin.Dictionary(argvalue1)
		arg96 := flag.Arg(3)
		mbTrans97 := thrift.NewTMemoryBufferLen(len(arg96))
		defer mbTrans97.Close()
		_, err98 := mbTrans97.WriteString(arg96)
		if err98 != nil {
			Usage()
			return
		}
		factory99 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt100 := factory99.GetProtocol(mbTrans97)
		containerStruct2 := admin.NewGetTableSplitsArgs()
		err101 := containerStruct2.ReadField3(jsProt100)
		if err101 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.StopKey
		value2 := admin.Dictionary(argvalue2)
		fmt.Print(client.GetTableSplits(value0, value1, value2))
		fmt.Print("\n")
		break
	case "queryMetric":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryMetric requires 1 args")
			flag.Usage()
		}
		arg102 := flag.Arg(1)
		mbTrans103 := thrift.NewTMemoryBufferLen(len(arg102))
		defer mbTrans103.Close()
		_, err104 := mbTrans103.WriteString(arg102)
		if err104 != nil {
			Usage()
			return
		}
		factory105 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt106 := factory105.GetProtocol(mbTrans103)
		argvalue0 := admin.NewMetricQueryRequest()
		err107 := argvalue0.Read(jsProt106)
		if err107 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryMetric(value0))
		fmt.Print("\n")
		break
	case "queryMetrics":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryMetrics requires 1 args")
			flag.Usage()
		}
		arg108 := flag.Arg(1)
		mbTrans109 := thrift.NewTMemoryBufferLen(len(arg108))
		defer mbTrans109.Close()
		_, err110 := mbTrans109.WriteString(arg108)
		if err110 != nil {
			Usage()
			return
		}
		factory111 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt112 := factory111.GetProtocol(mbTrans109)
		containerStruct0 := admin.NewQueryMetricsArgs()
		err113 := containerStruct0.ReadField1(jsProt112)
		if err113 != nil {
			Usage()
			return
		}
		argvalue0 := containerStruct0.Queries
		value0 := argvalue0
		fmt.Print(client.QueryMetrics(value0))
		fmt.Print("\n")
		break
	case "findAllAppInfo":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "FindAllAppInfo requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.FindAllAppInfo())
		fmt.Print("\n")
		break
	case "getTableSize":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTableSize requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetTableSize(value0))
		fmt.Print("\n")
		break
	case "getServerVersion":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetServerVersion requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetServerVersion())
		fmt.Print("\n")
		break
	case "validateClientVersion":
		if flag.NArg()-1 != 1 {
			fmt.Fprintln(os.Stderr, "ValidateClientVersion requires 1 args")
			flag.Usage()
		}
		arg115 := flag.Arg(1)
		mbTrans116 := thrift.NewTMemoryBufferLen(len(arg115))
		defer mbTrans116.Close()
		_, err117 := mbTrans116.WriteString(arg115)
		if err117 != nil {
			Usage()
			return
		}
		factory118 := thrift.NewTSimpleJSONProtocolFactory()
		jsProt119 := factory118.GetProtocol(mbTrans116)
		argvalue0 := admin.NewVersion()
		err120 := argvalue0.Read(jsProt119)
		if err120 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ValidateClientVersion(value0))
		fmt.Print("\n")
		break
	case "getServerTime":
		if flag.NArg()-1 != 0 {
			fmt.Fprintln(os.Stderr, "GetServerTime requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetServerTime())
		fmt.Print("\n")
		break
	case "":
		Usage()
		break
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
