// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package errors

import (
	"bytes"
	"fmt"
	"github.com/XiaoMi/galaxy-sdk-go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var ERROR_AUTO_BACKOFF map[ErrorCode]int32

const MAX_RETRY = 1

func init() {
	ERROR_AUTO_BACKOFF = map[ErrorCode]int32{
		2:  1000,
		25: 1000,
		32: 0,
	}

}
