// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package errors

import (
	"bytes"
	"fmt"
	"github.com/XiaoMi/galaxy-sdk-go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var ERROR_BACKOFF map[ErrorCode]int64
var ERROR_RETRY_TYPE map[ErrorCode]RetryType
const MAX_RETRY = 1

func init() {
ERROR_BACKOFF = map[ErrorCode]int64{
    2: 10,
    25: 10,
    37: 0,
    32: 0,
    1: 10,
    35: 10,
}

ERROR_RETRY_TYPE = map[ErrorCode]RetryType{
    2:   0,
    25:   0,
    37:   0,
    32:   0,
    1:   1,
    35:   1,
}

}

