// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package auth

import (
	"bytes"
	"fmt"
	"github.com/XiaoMi/galaxy-sdk-go/sds/common"
	"github.com/XiaoMi/galaxy-sdk-go/sds/errors"
	"github.com/XiaoMi/galaxy-sdk-go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = errors.GoUnusedProtection__
var _ = common.GoUnusedProtection__
var SIGNATURE_SUPPORT map[UserType]bool

const HK_AUTHORIZATION = "Authorization"
const HK_HOST = "Host"
const HK_TIMESTAMP = "X-Xiaomi-Timestamp"
const HK_CONTENT_MD5 = "X-Xiaomi-Content-MD5"
const HK_VERSION = "X-Xiaomi-Version"
const HK_USER_TYPE = "X-Xiaomi-User-Type"
const HK_SECRET_KEY_ID = "X-Xiaomi-Secret-Key-Id"
const HK_SECRET_KEY = "X-Xiaomi-Secret-Key"
const HK_SIGNATURE = "X-Xiaomi-Signature"
const HK_MAC_ALGORITHM = "X-Xiaomi-Mac-Algorithm"
const HK_SUPPORT_ACCOUNT_KEY = "X-Xiaomi-Support-Account-Key"

var SUGGESTED_SIGNATURE_HEADERS []string

func init() {
	SIGNATURE_SUPPORT = map[UserType]bool{
		1:  false,
		2:  true,
		10: true,
		11: true,
		12: false,
		13: false,
	}

	SUGGESTED_SIGNATURE_HEADERS = []string{
		"Host", "X-Xiaomi-Timestamp", "X-Xiaomi-Content-MD5"}

}
