// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package constants

import (
	"bytes"
	"fmt"
	"github.com/XiaoMi/galaxy-sdk-go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

const DEFAULT_CLIENT_SOCKET_TIMEOUT = 60000
const DEFAULT_CLIENT_CONN_TIMEOUT = 30000
const DEFAULT_SERVICE_ENDPOINT = "http://awsbj0.emq.api.xiaomi.com"
const DEFAULT_SECURE_SERVICE_ENDPOINT = "https://awsbj0.emq.api.xiaomi.com"
const QUEUE_SERVICE_PATH = "/v1/api/queue"
const MESSAGE_SERVICE_PATH = "/v1/api/message"
const STATISTICS_SERVICE_PATH = "/v1/api/statistics"
const XIAOMI_HEADER_PREFIX = "x-xiaomi-"
const MI_DATE = "x-xiaomi-date"
const GALAXY_ACCESS_KEY_ID = "GalaxyAccessKeyId"
const SIGNATURE = "Signature"
const AUTHORIZATION = "authorization"
const CONTENT_MD5 = "content-md5"
const CONTENT_TYPE = "content-type"
const DATE = "date"
const RANGE = "range"
const USER_AGENT = "user-agent"
const HOST = "host"
const TIMESTAMP = "x-xiaomi-timestamp"
const CONTENT_LENGTH = "content-length"

func init() {
}
